version: '3'
services:
  humhub:
    build: .
    ports:
      - "127.0.0.1:8080:80"
    volumes:
      - .:/var/www/html/admin/
      - /var/www/humhub:/var/www/html  
      - /var/run/mysqld/mysqld.sock:/var/lib/mysql/mysql.sock 
    extra_hosts:
      - "smtp-server:172.18.0.1"
